ime: str = input("Dragi korisnice unesi svoje ime> ")
prezime: str = input("Dragi korisnice unesi svoje prezime> ")
godina_rodenja: int = int(input("Dragi korisnice unesi godinu rodenja> "))
drzava_rodenja: str = input("Dragi korisnice unesi drzavu rodenja> ")
status_radnog_odnosa: str = input("Dragi korisnice unesi unesi (zaposlen/nezaposlen)> ")
jesi_li_zaposlen: bool = bool(input("Dragi korisnice unesi unesi (Da/Ne)> "))  # bug
zaposlen: bool = True
tezina_kg: float = float(input("Dragi korisnice unesi masu u kg> "))
spol: str = input("Dragi korisnice unesi spol (M/Z)> ")

print("Ime:", ime)
print("Prezime:", prezime)
print("Godina rodenja:", godina_rodenja)
print("Status radnog odnosa:", status_radnog_odnosa)
print("Zaposlen:", zaposlen)
print("Tezina:", tezina_kg, "kg")
print("Spol:", spol)

print("\n\n")

print("Ime:", end=" ")
print(ime)
print("Prezime:", end=" ")
print(prezime)
print("Godina rodenja:", end=" ")
print(godina_rodenja)
print("Status radnog odnosa:", end=" ")
print(status_radnog_odnosa)
print("Zaposlen:", end=" ")
print(zaposlen)
print("Tezina:", end=" ")
print(tezina_kg, end=" ")
print("kg")
print("Spol:", end=" ")
print(spol)
